DEBUG = True
COLOR_SPACE = 'YCrCb' # Can be RGB, HSV, LUV, HLS, YUV, YCrCb
ORIENT = 9  # HOG orientations
PIX_PER_CELL = 8 # HOG pixels per cell
CELL_PER_BLOCK = 2 # HOG cells per block
HOG_CHANNEL = "ALL" # Can be 0, 1, 2, or "ALL"
SPATIAL_SIZE = (32, 32) # Spatial binning dimensions
HIST_BINS = 32    # Number of histogram bins
SPATIAL_FEAT = True # Spatial features on or off
HIST_FEAT = True # Histogram features on or off
HOG_FEAT = True # HOG features on or off
X_START_STOP = [None, None] # Min and max in y to search in slide_window()
Y_START_STOP = [400, 656] # Min and max in y to search in slide_window()
SCALE = 1.5
CAR_CLASS = 1
NON_CAR_CLASS = 0
HEATMAP_THRESHOLD = 1
